# Generated by Django 3.1.2 on 2020-10-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
                ('TipoUsuario', models.CharField(choices=[('Medico', 'Medico'), ('Paciente', 'Paciente'), ('Especialista', 'Especialista')], default='Medico', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Incapacidades',
            new_name='Incapacitaciones',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Estrato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='IdGrupoFamiliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.grupofamiliar', verbose_name='Identificador del GrupoFamiliar'),
        ),
    ]
